# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog2(object):
    def setupUiDialog2(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(290, 154)
        self.pushButton_6 = QtWidgets.QDialogButtonBox(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(90, 100, 101, 31))
        self.pushButton_6.setObjectName("pushButton")

        #self.buttonBox_6 = QtWidgets.QDialogButtonBox(Dialog)
        # self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.pushButton_6.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.pushButton_6.accepted.connect(Dialog.accept)


        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 30, 141, 51))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "About"))
        # self.pushButton_6.setText(_translate("Dialog", "OK"))


        self.label.setText(_translate("Dialog", "Verepainemittaukset vertailu"))
